from __future__ import annotations

from typing import Any, Protocol, TypeVar

from sqlalchemy.orm.attributes import InstrumentedAttribute

T = TypeVar("T")


class GenericRepository(Protocol[T]):
    async def save(self, entity: T) -> T: ...
    async def get_all(self) -> list[T]: ...
    async def count(self) -> int: ...
    async def get_by_id(self, id: int) -> T | None: ...
    async def get_by(self, attr: InstrumentedAttribute, value: Any) -> T | None: ...
    async def find_all_by(self, attr: InstrumentedAttribute, value: Any) -> list[T]: ...
    async def exist_by(self, attr: InstrumentedAttribute, value: Any) -> bool: ...
    async def delete_by_id(self, id: int) -> None: ...
    async def bulk_save(self, entities: list[T]) -> list[T]: ...
    async def bulk_delete(self, ids: list[int]) -> None: ...
    async def paginate(self, page: int, size: int) -> tuple[list[T], int]: ...
