"""add_plans_table

Revision ID: e000e859272d
Revises: 5d0ab2135541
Create Date: 2026-05-21 20:03:06.323993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e000e859272d'
down_revision: Union[str, Sequence[str], None] = '5d0ab2135541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('face_limit', sa.BigInteger(), nullable=False),
    sa.Column('request_limit_per_month', sa.BigInteger(), nullable=False),
    sa.Column('extra_face_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extra_request_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    # ### end Alembic commands ###
