from pydantic import BaseModel, ConfigDict, Field


class InvalidParam(BaseModel):
    """Details about a specific invalid field in the request."""

    name: str = Field(..., description="The name of the invalid parameter or field.")
    reason: str = Field(
        ..., description="A human-readable explanation of why it is invalid."
    )


class ProblemDetailsModel(BaseModel):
    """Strict error payload structure according to RFC 7807 with custom extensions."""

    model_config = ConfigDict(extra="ignore")

    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type.",
    )
    title: str = Field(
        ..., description="A short, human-readable summary of the problem type."
    )
    status: int = Field(
        ..., description="The HTTP status code generated by the origin server."
    )
    detail: str = Field(
        ..., description="A human-readable explanation specific to this occurrence."
    )
    instance: str | None = Field(
        default=None,
        description="A URI reference that identifies the specific occurrence of the problem.",
    )

    invalid_params: list[InvalidParam] | None = Field(
        default=None,
        description="A list of invalid parameters that caused the error (if applicable).",
    )